# Data-driven Aspects

---
Loyola University Chicago  
COMP 379-001/479-001, Spring 2025, Machine Learning  
Instructor: Daniel Moreira (dmoreira1@luc.edu)  
More at https://danielmoreira.github.io/teaching/ml-spr25/

---

Practical examples and exercises of the data-driven aspects of Machine Learning.

Language: Python 3  

Needed libraries:
* NumPy (https://numpy.org/)
* Pandas (https://pandas.pydata.org/)
* Scikit-learn (https://scikit-learn.org/)

-------
## Data Partition

In [5]:
# download the wine dataset
!curl -O https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10782    0 10782    0     0  34159      0 --:--:-- --:--:-- --:--:-- 34228


In [6]:
import numpy as np
import pandas as pd

# loads the wine dataset into memory
df_wine = pd.read_csv('/content/wine.data')

# adds headers to the dataset according to documentation
df_wine.columns = [
    'label', 'alcohol', 'malic acid', 'ash', 'alcalinity', 'magnesium',
    'phenols', 'flavanoids', 'nonflavanoid phenols', 'proanthocyanins',
    'color intensity', 'hue', 'protein concentration', 'proline']

# prints info
print('Data shape:', df_wine.shape)
print('Labels, Label count:', np.unique(df_wine['label'], return_counts=True))
print()

# first 10 samples
df_wine.head(10)

Data shape: (177, 14)
Labels, Label count: (array([1, 2, 3]), array([58, 71, 48]))



label  alcohol  malic acid   ash  alcalinity  magnesium  phenols  \
0      1    13.20        1.78  2.14        11.2        100     2.65   
1      1    13.16        2.36  2.67        18.6        101     2.80   
2      1    14.37        1.95  2.50        16.8        113     3.85   
3      1    13.24        2.59  2.87        21.0        118     2.80   
4      1    14.20        1.76  2.45        15.2        112     3.27   
5      1    14.39        1.87  2.45        14.6         96     2.50   
6      1    14.06        2.15  2.61        17.6        121     2.60   
7      1    14.83        1.64  2.17        14.0         97     2.80   
8      1    13.86        1.35  2.27        16.0         98     2.98   
9      1    14.10        2.16  2.30        18.0        105     2.95   

   flavanoids  nonflavanoid phenols  proanthocyanins  color intensity   hue  \
0        2.76                  0.26             1.28             4.38  1.05   
1        3.24                  0.30             2.81             5.68  1.03   
2        3.49                  0.24             2.18             7.80  0.86   
3        2.69                  0.39             1.82             4.32  1.04   
4        3.39                  0.34             1.97             6.75  1.05   
5        2.52                  0.30             1.98             5.25  1.02   
6        2.51                  0.31             1.25             5.05  1.06   
7        2.98                  0.29             1.98             5.20  1.08   
8        3.15                  0.22             1.85             7.22  1.01   
9        3.32                  0.22             2.38             5.75  1.25   

   protein concentration  proline  
0                   3.40     1050  
1                   3.17     1185  
2                   3.45     1480  
3                   2.93      735  
4                   2.85     1450  
5                   3.58     1290  
6                   3.58     1295  
7                   2.85     1045  
8                   3.55     1045  
9                   3.17     1510

In [7]:
# data partition using sklearn
# reference: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
from sklearn.model_selection import train_test_split

# separation into data (X) and respective labels (y)
X, y = df_wine.iloc[:, 1:].values, df_wine.iloc[:, 0].values
print('First 10 samples:', X[:10])
print('First 10 labels:', y[:10])
print()

# split configuration
test_size = 0.3 # data percentage going to test
random_seed = 0 # save the seed for reproducibility

# data split
X_train, X_test, y_train, y_test =\
  train_test_split(X, y,
                   random_state=random_seed,
                   test_size=test_size,
                   stratify=y)

# train info
print('Train data shape:', X_train.shape)
print('Train data labels, label count:', np.unique(y_train, return_counts=True))
print()

First 10 samples: [[1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]
 [1.420e+01 1.760e+00 2.450e+00 1.520e+01 1.120e+02 3.270e+00 3.390e+00
  3.400e-01 1.970e+00 6.750e+00 1.050e+00 2.850e+00 1.450e+03]
 [1.439e+01 1.870e+00 2.450e+00 1.460e+01 9.600e+01 2.500e+00 2.520e+00
  3.000e-01 1.980e+00 5.250e+00 1.020e+00 3.580e+00 1.290e+03]
 [1.406e+01 2.150e+00 2.610e+00 1.760e+01 1.210e+02 2.600e+00 2.510e+00
  3.100e-01 1.250e+00 5.050e+00 1.060e+00 3.580e+00 1.295e+03]
 [1.483e+01 1.640e+00 2.170e+00 1.400

### Exercise 1
Print info about the test partition.

In [8]:
# add your code here
print('Test data shape:', X_test.shape)
print('Test data labels, label count:', np.unique(y_test, return_counts=True))
print()

Test data shape: (54, 13)
Test data labels, label count: (array([1, 2, 3]), array([18, 22, 14]))



-------
## Data Preprocessing


### Numerical Data

In [9]:
# download the California housing dataset
!pip install gdown==v5.1.0
!gdown 1QkyFNJR8CloAprShjVz7QR8L0e1UuJOf

Downloading...
From: https://drive.google.com/uc?id=1QkyFNJR8CloAprShjVz7QR8L0e1UuJOf
To: /content/housing.csv
100% 1.42M/1.42M [00:00<00:00, 120MB/s]


In [10]:
import numpy as np
import pandas as pd

# loads the housing dataset into memory
df_housing = pd.read_csv('/content/housing.csv')

# prints info
print('Data shape:', df_housing.shape)
print('All features numerical but last one.')

# last 5 samples
df_housing.tail(5)

Data shape: (20640, 10)
All features numerical but last one.


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND

#### Exercise 2
By using the official [Scikit-learn reference](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html), split the California housing dataset into *train* and *test*, with the test partition containing half of the data.

In [12]:
# add your code here

X = df_housing.values

# split configuration
test_size = 0.5 # data percentage going to test
random_seed = 0 # save the seed for reproducibility

# data split
X_train, X_test =\
  train_test_split(X,
                   random_state=random_seed,
                   test_size=test_size)

# train info
print('Train data shape:', X_train.shape)
print()

# test info
print('Train data shape:', X_test.shape)
print()


Train data shape: (10320, 10)

Train data shape: (10320, 10)



### Ordinal Data

In [13]:
# toy-case example
import pandas as pd

df = pd.DataFrame([['green', 'M', 10.1],
                   ['red', 'L', 13.5],
                   ['blue', 'XL', 15.3],
                   ['green', 'S', 8.9]])

df.columns = ['color', 'size', 'price']
df

color size  price
0  green    M   10.1
1    red    L   13.5
2   blue   XL   15.3
3  green    S    8.9

In [14]:
# ordinal data mapping to numerical
size_mapping = {'XL': 3,
                'L': 2,
                'M': 1,
                'S': 0}

df['size'] = df['size'].map(size_mapping)
df

color  size  price
0  green     1   10.1
1    red     2   13.5
2   blue     3   15.3
3  green     0    8.9

In [15]:
# inverse mapping, to allow further explanation
inv_size_mapping = {v: k for k, v in size_mapping.items()}
df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
3     S
Name: size, dtype: object

### Nominal Data

In [16]:
# one-hot encoding example but with colinearity

# needed libraries
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# column transformation
X = df.values
encoder = OneHotEncoder()
transformer = ColumnTransformer([('onehot', encoder, [0]), #[0]: color column
                               ('keep', 'passthrough', [1, 2])])
X_transf = transformer.fit_transform(X).astype(float)
print(X_transf)

# pandas format
df_transf = pd.DataFrame(X_transf)
df_transf.columns = ['color_blue', 'color_green', 'color_red', 'size', 'price']
df_transf

[[ 0.   1.   0.   1.  10.1]
 [ 0.   0.   1.   2.  13.5]
 [ 1.   0.   0.   3.  15.3]
 [ 0.   1.   0.   0.   8.9]]


color_blue  color_green  color_red  size  price
0         0.0          1.0        0.0   1.0   10.1
1         0.0          0.0        1.0   2.0   13.5
2         1.0          0.0        0.0   3.0   15.3
3         0.0          1.0        0.0   0.0    8.9

#### Exercise 3

**Question**

What is the problem with this solution in terms of *colinearity*?

> Problem of dependence, where each of the columns are dependent on the other categorization columns not being true (a red shirt needs green and blue quantities to be 0, and vice versa for the other shirts). This makes it difficult to specifically pinpoint which shirt is the frontrunner (given a scenario where two out of the three categories aren't 0).
>

In [17]:
# one-hot encoding example WITHOUT colinearity

# needed libraries
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# column transformation
X = df.values
encoder = OneHotEncoder(categories='auto', drop='first') # attention here!
transformer = ColumnTransformer([ ('onehot', encoder, [0]), #[0]: color column
                               ('keep', 'passthrough', [1, 2])])
X_transf = transformer.fit_transform(X).astype(float)
print(X_transf)

# pandas format
df_transf = pd.DataFrame(X_transf)
df_transf.columns = ['color_green', 'color_red', 'size', 'price']
df_transf

[[ 1.   0.   1.  10.1]
 [ 0.   1.   2.  13.5]
 [ 0.   0.   3.  15.3]
 [ 1.   0.   0.   8.9]]


color_green  color_red  size  price
0          1.0        0.0   1.0   10.1
1          0.0        1.0   2.0   13.5
2          0.0        0.0   3.0   15.3
3          1.0        0.0   0.0    8.9

#### Exercise 4

**Question**

How do you say if a shirt is blue?

> By deleting one of the encoded columns, in this case the blue column, we solve the collinearity problem, verifying that a shirt is blue if the encoding for both a green and red shirt in any given case are zeroes.
>

#### Exercise 5
Handle the "*ocean proximity*" column within the California dataset **train partition**.

In [18]:
# Check the available ocean proximity values
sorted(df_housing['ocean_proximity'].unique())

['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN']

In [19]:
# column transformation
encoder = OneHotEncoder(categories='auto', drop='first') # attention here!
transformer = ColumnTransformer([ ('onehot', encoder, [9]), #[0]: color column
                               ('keep', 'passthrough', [0, 1, 2, 3, 4, 5, 6, 7, 8])])
X_train_transf = transformer.fit_transform(X_train).astype(float)
print(X_train_transf)

# pandas format
df_train_transf = pd.DataFrame(X_train_transf)
df_train_transf.columns = ['INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'] + list(df_housing.columns[:9])
df_train_transf

[[1.0000e+00 0.0000e+00 0.0000e+00 ... 5.0300e+02 1.2450e+00 1.3750e+05]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 4.8100e+02 2.4432e+00 1.8750e+05]
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 4.4000e+02 2.4659e+00 1.7780e+05]
 ...
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 3.9300e+02 3.1977e+00 2.8930e+05]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 4.6800e+02 5.6315e+00 4.8460e+05]
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 2.9800e+02 1.3882e+00 6.9400e+04]]


INLAND  ISLAND  NEAR BAY  NEAR OCEAN  longitude  latitude  \
0         1.0     0.0       0.0         0.0    -121.48     38.58   
1         0.0     0.0       0.0         0.0    -118.16     33.96   
2         1.0     0.0       0.0         0.0    -116.41     33.74   
3         0.0     0.0       0.0         0.0    -118.28     33.92   
4         0.0     0.0       0.0         0.0    -118.20     33.96   
...       ...     ...       ...         ...        ...       ...   
10315     1.0     0.0       0.0         0.0    -121.26     38.27   
10316     1.0     0.0       0.0         0.0    -120.89     37.48   
10317     0.0     0.0       0.0         1.0    -121.90     36.58   
10318     0.0     0.0       0.0         0.0    -117.93     33.62   
10319     1.0     0.0       0.0         0.0    -115.56     32.80   

       housing_median_age  total_rooms  total_bedrooms  population  \
0                    42.0       1823.0           566.0       761.0   
1                    24.0       1635.0           507.0      2480.0   
2                    17.0       4289.0           893.0       958.0   
3                    39.0       1274.0           282.0       975.0   
4                    41.0       1512.0           400.0      1690.0   
...                   ...          ...             ...         ...   
10315                20.0       1314.0           229.0       712.0   
10316                27.0       1118.0           195.0       647.0   
10317                31.0       1431.0             NaN       704.0   
10318                34.0       2125.0           498.0      1052.0   
10319                15.0       1171.0           328.0      1024.0   

       households  median_income  median_house_value  
0           503.0         1.2450            137500.0  
1           481.0         2.4432            187500.0  
2           440.0         2.4659            177800.0  
3           277.0         1.5114             90400.0  
4           367.0         3.0550            167000.0  
...           ...            ...                 ...  
10315       219.0         4.4125            144600.0  
10316       209.0         2.9135            159400.0  
10317       393.0         3.1977            289300.0  
10318       468.0         5.6315            484600.0  
10319       298.0         1.3882             69400.0  

[10320 rows x 13 columns]

#### Exercise 6
Handle the "*ocean proximity*" column within the California dataset **test partition**.

> Don't contaminate the data!

In [20]:
# column transformation
X_test_transf = transformer.transform(X_test).astype(float)
print(X_test_transf)

# pandas format
df_test_transf = pd.DataFrame(X_test_transf)
df_test_transf.columns = ['INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'] + list(df_housing.columns[:9])
df_test_transf

[[0.00000e+00 0.00000e+00 0.00000e+00 ... 3.71000e+02 4.15180e+00
  1.36900e+05]
 [0.00000e+00 0.00000e+00 0.00000e+00 ... 4.29000e+02 5.77960e+00
  2.41300e+05]
 [1.00000e+00 0.00000e+00 0.00000e+00 ... 5.34000e+02 4.34870e+00
  2.00700e+05]
 ...
 [0.00000e+00 0.00000e+00 0.00000e+00 ... 5.35000e+02 3.74370e+00
  2.41700e+05]
 [0.00000e+00 0.00000e+00 1.00000e+00 ... 5.10000e+02 8.07550e+00
  5.00001e+05]
 [1.00000e+00 0.00000e+00 0.00000e+00 ... 3.33000e+02 1.77080e+00
  5.90000e+04]]


INLAND  ISLAND  NEAR BAY  NEAR OCEAN  longitude  latitude  \
0         0.0     0.0       0.0         1.0    -117.05     32.58   
1         0.0     0.0       0.0         0.0    -117.97     33.92   
2         1.0     0.0       0.0         0.0    -121.84     38.65   
3         1.0     0.0       0.0         0.0    -115.60     33.20   
4         0.0     0.0       1.0         0.0    -122.43     37.79   
...       ...     ...       ...         ...        ...       ...   
10315     0.0     0.0       0.0         1.0    -120.86     35.40   
10316     0.0     0.0       0.0         0.0    -121.79     36.64   
10317     0.0     0.0       0.0         0.0    -118.21     34.10   
10318     0.0     0.0       1.0         0.0    -122.42     37.80   
10319     1.0     0.0       0.0         0.0    -122.17     40.11   

       housing_median_age  total_rooms  total_bedrooms  population  \
0                    22.0       2101.0           399.0      1551.0   
1                    32.0       2620.0           398.0      1296.0   
2                    29.0       3167.0           548.0      1554.0   
3                    37.0        709.0           187.0       390.0   
4                    25.0       1637.0           394.0       649.0   
...                   ...          ...             ...         ...   
10315                21.0       2787.0           641.0      1106.0   
10316                11.0      32627.0          6445.0     28566.0   
10317                36.0       2000.0           533.0      1234.0   
10318                52.0       2852.0           581.0       838.0   
10319                24.0       1631.0           340.0      1042.0   

       households  median_income  median_house_value  
0           371.0         4.1518            136900.0  
1           429.0         5.7796            241300.0  
2           534.0         4.3487            200700.0  
3           142.0         2.4511             72500.0  
4           379.0         5.0049            460000.0  
...           ...            ...                 ...  
10315       501.0         2.7043            186200.0  
10316      6082.0         2.3087            118800.0  
10317       535.0         3.7437            241700.0  
10318       510.0         8.0755            500001.0  
10319       333.0         1.7708             59000.0  

[10320 rows x 13 columns]

#### Exercise 7

**Question**

How did you avoid contaminating the test set?

> I avoided contaminating the test set by only using parameters that were learned from the train partition. Recalculating these parameters on the test set would have contaminated it. The first line where transform is being applied to X_test indicates this, applying the same transformations that were applied on the training data. No new tranformations/calculations were applied on the test set, and so, it was left uncontaminated.
>

### Missing Data

In [21]:
# toy-case example
import pandas as pd
from io import StringIO

csv_data = \
'''A,B,C,D,E,F,G
1.0,2.0,3.0,4.0,5.0,6.0,7.0
8.0,9.0,,11.0,,13.0,14.0
15.0,16.0,17.0,,,,21.0
22.0,23.0,24.0,25.0,26.0,27.0,28.0'''

df = pd.read_csv(StringIO(csv_data))
print(df.values)
print()

df

[[ 1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. nan 11. nan 13. 14.]
 [15. 16. 17. nan nan nan 21.]
 [22. 23. 24. 25. 26. 27. 28.]]



A     B     C     D     E     F     G
0   1.0   2.0   3.0   4.0   5.0   6.0   7.0
1   8.0   9.0   NaN  11.0   NaN  13.0  14.0
2  15.0  16.0  17.0   NaN   NaN   NaN  21.0
3  22.0  23.0  24.0  25.0  26.0  27.0  28.0

#### Feature Drop

In [22]:
# drop columns that have one or more missing values
df_transf = df.dropna(axis=1)
df_transf

A     B     G
0   1.0   2.0   7.0
1   8.0   9.0  14.0
2  15.0  16.0  21.0
3  22.0  23.0  28.0

In [23]:
# drop columns that have fewer than <3> non-empty values
# i.e., all columns must have at least 3 non-empty values
df_transf = df.dropna(axis=1, thresh=3)
df_transf

A     B     C     D     F     G
0   1.0   2.0   3.0   4.0   6.0   7.0
1   8.0   9.0   NaN  11.0  13.0  14.0
2  15.0  16.0  17.0   NaN   NaN  21.0
3  22.0  23.0  24.0  25.0  27.0  28.0

#### Sample Drop


In [24]:
# drop rows that have one or more missing values
df_transf = df.dropna(axis=0)
df_transf

A     B     C     D     E     F     G
0   1.0   2.0   3.0   4.0   5.0   6.0   7.0
3  22.0  23.0  24.0  25.0  26.0  27.0  28.0

In [25]:
# drop rows that have fewer than <5> non-empty values
# i.e., all rows must have at least 5 non-empty values
df_transf = df.dropna(axis=0, thresh=5)
df_transf

A     B     C     D     E     F     G
0   1.0   2.0   3.0   4.0   5.0   6.0   7.0
1   8.0   9.0   NaN  11.0   NaN  13.0  14.0
3  22.0  23.0  24.0  25.0  26.0  27.0  28.0

In [26]:
# drop rows whose specific columns have missing values
df_transf = df.dropna(subset=['D', 'F']) # D and F cannot have missing values
df_transf

A     B     C     D     E     F     G
0   1.0   2.0   3.0   4.0   5.0   6.0   7.0
1   8.0   9.0   NaN  11.0   NaN  13.0  14.0
3  22.0  23.0  24.0  25.0  26.0  27.0  28.0

#### Value Replacement

In [27]:
# original values, for reference
df

A     B     C     D     E     F     G
0   1.0   2.0   3.0   4.0   5.0   6.0   7.0
1   8.0   9.0   NaN  11.0   NaN  13.0  14.0
2  15.0  16.0  17.0   NaN   NaN   NaN  21.0
3  22.0  23.0  24.0  25.0  26.0  27.0  28.0

In [28]:
# replaces missing values with column-wise mean values
mean = df.mean()
df_transf = df.fillna(mean)
df_transf

A     B          C          D     E          F     G
0   1.0   2.0   3.000000   4.000000   5.0   6.000000   7.0
1   8.0   9.0  14.666667  11.000000  15.5  13.000000  14.0
2  15.0  16.0  17.000000  13.333333  15.5  15.333333  21.0
3  22.0  23.0  24.000000  25.000000  26.0  27.000000  28.0

In [29]:
# replaces columns C and D with mean, and E and F with max
mean = df.mean()
max = df.max()

df_transf = df.copy()
df_transf[['C', 'D']] = df[['C', 'D']].fillna(mean)
df_transf[['E', 'F']] = df[['E', 'F']].fillna(max)
df_transf

A     B          C          D     E     F     G
0   1.0   2.0   3.000000   4.000000   5.0   6.0   7.0
1   8.0   9.0  14.666667  11.000000  26.0  13.0  14.0
2  15.0  16.0  17.000000  13.333333  26.0  27.0  21.0
3  22.0  23.0  24.000000  25.000000  26.0  27.0  28.0

### Data Normalization

#### Data Scaling

In [30]:
# toy-case example (with train and test partition)
import pandas as pd

df_train = pd.DataFrame([[0.15, 1230, 0.00000005, 315.10],
                         [0.12, 4217, 0.00000027, 117.00],
                         [0.23,  943, 0.00000003, 230.40],
                         [0.18, 1014,        0.0,   3.14]])

df_test = pd.DataFrame([[0.25, 1500, 0.00000002,   3.14],
                        [0.16, 3500,        0.0, 100.00]])

df_train, df_test

(      0     1             2       3
 0  0.15  1230  5.000000e-08  315.10
 1  0.12  4217  2.700000e-07  117.00
 2  0.23   943  3.000000e-08  230.40
 3  0.18  1014  0.000000e+00    3.14,
       0     1             2       3
 0  0.25  1500  2.000000e-08    3.14
 1  0.16  3500  0.000000e+00  100.00)

In [31]:
# train data scale implementation
df_max = df_train.max()
df_min = df_train.min()

df_train_norm = (df_train - df_min) / (df_max - df_min)
df_train_norm

0         1         2         3
0  0.272727  0.087660  0.185185  1.000000
1  0.000000  1.000000  1.000000  0.364983
2  1.000000  0.000000  0.111111  0.728491
3  0.545455  0.021686  0.000000  0.000000

In [32]:
# test data scale normalization
df_max = df_train.max() # use the train data to avoid contamination!
df_min = df_train.min() # use the train data to avoid contamination!

df_test_norm = (df_test - df_min) / (df_max - df_min)
df_test_norm

0         1         2         3
0  1.181818  0.170128  0.074074  0.000000
1  0.363636  0.781002  0.000000  0.310489

In [33]:
# sklearn data scale implementation
from sklearn.preprocessing import MinMaxScaler

# scaler object
scaler = MinMaxScaler()

# train data
X_train = df_train.values
X_train_norm = scaler.fit_transform(X_train) # use fit only on the train set!

X_train_norm

array([[0.27272727, 0.08766035, 0.18518519, 1.        ],
       [0.        , 1.        , 1.        , 0.36498269],
       [1.        , 0.        , 0.11111111, 0.72849083],
       [0.54545455, 0.02168601, 0.        , 0.        ]])

In [34]:
# test data
X_test = df_test.values
X_test_norm = scaler.transform(X_test) # don't use fit on the test set!

X_test_norm

array([[1.18181818, 0.17012828, 0.07407407, 0.        ],
       [0.36363636, 0.78100183, 0.        , 0.31048852]])

#### Data Standardization

In [35]:
# same previous toy-case example (with train and test partition)
import pandas as pd

df_train = pd.DataFrame([[0.15, 1230, 0.00000005, 315.10],
                         [0.12, 4217, 0.00000027, 117.00],
                         [0.23,  943, 0.00000003, 230.40],
                         [0.18, 1014,        0.0,   3.14]])

df_test = pd.DataFrame([[0.25, 1500, 0.00000002,   3.14],
                        [0.16, 3500,        0.0, 100.00]])

df_train, df_test

(      0     1             2       3
 0  0.15  1230  5.000000e-08  315.10
 1  0.12  4217  2.700000e-07  117.00
 2  0.23   943  3.000000e-08  230.40
 3  0.18  1014  0.000000e+00    3.14,
       0     1             2       3
 0  0.25  1500  2.000000e-08    3.14
 1  0.16  3500  0.000000e+00  100.00)

In [36]:
# train data standardization
df_mean = df_train.mean()
df_std = df_train.std(ddof=0)

df_train_norm = (df_train - df_mean) / df_std
df_train_norm

0         1         2         3
0 -0.492366 -0.453254 -0.350931  1.264567
1 -1.230915  1.726889  1.707865 -0.420218
2  1.477098 -0.662728 -0.538095  0.544217
3  0.246183 -0.610907 -0.818839 -1.388566

In [37]:
# test data standardization
df_mean = df_train.mean()     # use the train data to avoid contamination!
df_std = df_train.std(ddof=0) # use the train data to avoid contamination!

df_test_norm = (df_test - df_mean) / df_std
df_test_norm

0         1         2         3
0  1.969464 -0.256187 -0.631676 -1.388566
1 -0.246183  1.203567 -0.818839 -0.564799

In [38]:
# sklearn implementation
from sklearn.preprocessing import StandardScaler

# scaler object
scaler = StandardScaler()

# train data
X_train = df_train.values
X_train_norm = scaler.fit_transform(X_train) # use fit only on the train set!

X_train_norm

array([[-0.49236596, -0.45325358, -0.3509312 ,  1.26456693],
       [-1.23091491,  1.72688884,  1.70786519, -0.42021825],
       [ 1.47709789, -0.66272826, -0.53809451,  0.54421708],
       [ 0.24618298, -0.610907  , -0.81883947, -1.38856576]])

In [39]:
# test data
X_test = df_test.values
X_test_norm = scaler.transform(X_test) # don't use fit on the test set!

X_test_norm

array([[ 1.96946386, -0.25618681, -0.63167617, -1.38856576],
       [-0.24618298,  1.20356708, -0.81883947, -0.56479851]])

#### Exercise 8

Execute data partition and preprocessing on the California housing dataset, which was provided above (see the "Numerical Data" section).   

Split the data into train and test partitions, with the test set containing 30% of the data.

Handle all the eventual categorical data, and replace all the missing values with the median of their respective features. Lastly, normalize the dataset with standardization. Make sure to avoid standardizing the columns with categorical data.

Make sure not to mix train and test partitions.   
**Do not contaminate the data!**


In [44]:
import numpy as np

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

X = df_housing.copy()

# split configuration
test_size = 0.3 # data percentage going to test
random_seed = 0 # save the seed for reproducibility

# data split
X_train, X_test =\
  train_test_split(X, # run prev sections for split var to work
                   random_state=random_seed,
                   test_size=test_size)

# train info
print('Train data shape:', X_train.shape)
print()

# test info
print('Train data shape:', X_test.shape)
print()


# data preprocessing
# finding categorical/numerical columns
categorical_features = ['ocean_proximity']
numerical_features = [col for col in X.columns if col not in categorical_features]

# deadling with missing vals, median insertion
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')), # replace missing ones with given median
    ('scaler', StandardScaler()) # standardizing --> zero mean, unit variance
    # standard scaler only calculates from train set and applies to test set
])

# handling categorical Data with one-hot encode
cat_pipeline = Pipeline([
    ('encoder', OneHotEncoder(handle_unknown='ignore')) # categories = now numerical form
])

# Combine Pipelines into ColumnTransformer
transformer = ColumnTransformer([
    ('num', num_pipeline, numerical_features),
    ('cat', cat_pipeline, categorical_features)
])

# transform data
X_train_transf = transformer.fit_transform(X_train)
X_test_transf = transformer.transform(X_test) # do not fit test data for transforms
# otherwise it'd be contaminated

df_train_transf = pd.DataFrame(X_train_transf)
df_test_transf = pd.DataFrame(X_test_transf)

print("\nCategorial data, missing values, preprocessing, and standardization complete")


Train data shape: (14448, 10)

Train data shape: (6192, 10)


Categorial data, missing values, preprocessing, and standardization complete
